import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={pretendard.className}>
      <body>
        <div className="relative w-[100dvw] h-[100dvh] bg-white">
          {children}
        </div>
      </body>
    </html>
  );
}
